Базовая стилизация всех страниц
htmlacademy-htmlcss/2011329-sedona-33 pull request #2
Opened 2022-02-27 04:33 UTC by Balder1984

---
:mortar_board: [Графика для всех страниц](https://up.htmlacademy.ru/htmlcss/33/user/2011329/tasks/5)

:boom: https://htmlacademy-htmlcss.github.io/2011329-sedona-33/2/

---
:mortar_board: [Базовая стилизация всех страниц](https://up.htmlacademy.ru/htmlcss/33/user/2011329/tasks/6)

2022-03-04 17:03 UTC, pavel-nyukalo requested changes
По поводу картинок:
вот эту картинку советую в `svg` экспортировать, поскольку дальше нам надо будет менять у нее цвета при наведении/нажатии
![image](https://user-images.githubusercontent.com/52506235/156805470-8be7a22d-d3eb-4ddc-aecb-28aedb1a6b82.png)

2022-03-04 17:03 UTC, pavel-niukalo commented on catalog.html
> +        </li>
Поскольку не с начала работаем, решил еще глянуть параллельно разметку.
Первое, что я бы предложил - пройтись по коду и внимательно расставить отступы вложенных элементов. По правилам editorconfig, отступы у нас в 2 пробела. Конкретно вот тут надо
```html
<ul>
  <li>
    <a></a>
  </li>
  ...
</ul>
```

2022-03-04 17:03 UTC, pavel-niukalo commented on catalog.html
> +      <p class="footer-contacts-address-phone">+7 812 812-12-12</p>
Телефоны необходимо разметить ссылками с [соответствующим атрибутом](https://htmlacademy.ru/blog/boost/frontend/mailto)

2022-03-04 17:03 UTC, pavel-niukalo commented on index.html
>          <ul class="advantages-list">
Здесь бы рекомендовал сделать `ol` - нумерованный список, у нас есть -№1- и тд, как раз нумерация

2022-03-04 17:03 UTC, pavel-niukalo commented on styles/styles.css
> +  }
Тут тоже надо поправить отступы во всем файле.
Например у `.page-header` есть лишний отступ в два пробела, должно быть 0 (как у перед `body`)

2022-03-04 17:03 UTC, pavel-niukalo commented on styles/styles.css
> +    font-family: "PT Sans", sans-serif;
Задав семейство шрифтов в `body` дальше можно не прописывать их, они наследуются
![image](https://user-images.githubusercontent.com/52506235/156806633-0b4bfa51-ab00-4d25-800d-2b2c7aadf4f1.png)

(Исключение `input`, `button`, `select`, им можно прописать потом будет `font-family: inherit`)

2022-03-04 17:03 UTC, pavel-niukalo commented on styles/styles.css
> +    height: 70;
Не указаны единицы

2022-03-04 17:03 UTC, pavel-niukalo commented on styles/styles.css
> +    height: 485;
Тоже не указаны единицы

2022-03-04 17:03 UTC, pavel-nyukalo commented on styles/styles.css
> +    line-height: 35;
И здесь, для уверенности лучше пройтись по всему коду, проверить

2022-03-04 17:03 UTC, pavel-niukalo commented on styles/styles.css
> +
Предлагаю пока файл не разросся сразу оформлять его чисто. Между селекторами оставлять только одну строку, не 4

2022-03-07 02:25 UTC, Balder1984 commented
Добрый день! 
*  Формат картинки поменял на SVG/
*   По отступам, прошу дать более развёрнутую формулировку, не совсем понимаю что от меня требуется (отступы вроде в следующих заданиях регулируются???).
*  Телефон в ссылку с соответствующим атрибутом разместил.
*  Список на  нумерованный поменял.
*  Отступы во всем файле — вроде поправил, прошу посмотреть верно ли?
*  Все единицы измерение проставил.
*  4 строчки между селекторами убрал. 
>Пятница, 4 марта 2022, 20:03 +03:00 от Pavel Nyukalo ***@***.***>:
> 
> 
***@***.*** requested changes on this pull request.
>По поводу картинок:
>вот эту картинку советую в svg экспортировать, поскольку дальше нам надо будет менять у нее цвета при наведении/нажатии
>----------------------------------------------------------------------
>In  catalog.html :
>> +        <ul class="photo-menu">
>+        <li class="photo-menu-button">
>         <a href="#" class="button button-light">
>             <span class="visually-hidden">Показать карточки</span>
>           </a>
>+        </li>
>
>Поскольку не с начала работаем, решил еще глянуть параллельно разметку.
>Первое, что я бы предложил - пройтись по коду и внимательно расставить отступы вложенных элементов. По правилам editorconfig, отступы у нас в 2 пробела. Конкретно вот тут надо
><ul>
>  <li>
>    <a></a>
>  </li>
>  ...
></ul>
>----------------------------------------------------------------------
>In  catalog.html :
>> +          <a class="button" href="https://twitter.com/htmlacademy_ru">
>+            <span class="visually-hidden">Твиттер</span>
>+          </a>
>+        </li>
>+        <li class="footer-social-item">
>+         <a class="button" href="https://www.facebook.com/htmlacademy">
>+          <span class="visually-hidden">Файсбук</span>
>+         </a>
>+        </li>
>+        <li class="footer-social-item">
>+         <a class="button" href="https://www.youtube.com/c/HTMLAcademyRUS">
>+          <span class="visually-hidden">Ютуб</span>
>+         </a>
>+        </li>
>+      </ul>
>+      <p class="footer-contacts-address-phone">+7 812 812-12-12</p>
>
>Телефоны необходимо разметить ссылками с  соответствующим атрибутом
>----------------------------------------------------------------------
>In  index.html :
>>           <p>Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</p>
>-      </section>
>+      </section>      
>+  <div class="index-columns">
>       <section class="advantages">
>         <h2 class="visually-hidden">Преимущества</h2>
>         <ul class="advantages-list">
>
>Здесь бы рекомендовал сделать ol - нумерованный список, у нас есть -№1- и тд, как раз нумерация
>----------------------------------------------------------------------
>In  styles/styles.css :
>> +body {
>+  font-family: "PT Sans", sans-serif;
>+  font-size: 16px;
>+  line-height: 24px;
>+  color: #242424;
>+  background-color: #fbf7f4;
>+  text-align: center; 
>+  }
>+
>+  .page-header {
>+    color: #000000;
>+    background-color: #E5E5E5;
>+    width: 1060;
>+    height: 70;
>+  }
>
>Тут тоже надо поправить отступы во всем файле.
>Например у .page-header есть лишний отступ в два пробела, должно быть 0 (как у перед body)
>----------------------------------------------------------------------
>In  styles/styles.css :
>> +  font-size: 16px;
>+  line-height: 24px;
>+  color: #242424;
>+  background-color: #fbf7f4;
>+  text-align: center; 
>+  }
>+
>+  .page-header {
>+    color: #000000;
>+    background-color: #E5E5E5;
>+    width: 1060;
>+    height: 70;
>+  }
>+
>+  .navigation-link {
>+    font-family: "PT Sans", sans-serif; 
>
>Задав семейство шрифтов в body дальше можно не прописывать их, они наследуются
>(Исключение input, button, select, им можно прописать потом будет font-family: inherit)
>----------------------------------------------------------------------
>In  styles/styles.css :
>> +    width: 1060;
>+    height: 70;
>
>Не указаны единицы
>----------------------------------------------------------------------
>In  styles/styles.css :
>> +    width: 1200;
>+    height: 485;
>
>Тоже не указаны единицы
>----------------------------------------------------------------------
>In  styles/styles.css :
>> +    font-size: 24;
>+    line-height: 35;
>
>И здесь, для уверенности лучше пройтись по всему коду, проверить
>----------------------------------------------------------------------
>In  styles/styles.css :
>> +  
>+  
>+ 
>+ 
>
>Предлагаю пока файл не разросся сразу оформлять его чисто. Между селекторами оставлять только одну строку, не 4
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <htmlacademy-htmlcss/2011329-sedona-33/pull/2/review/900460364 @ github . com>
 
 
--
Марк Галицкий
Отправлено из Почты  Mail.ru
 

2022-03-10 08:23 UTC, pavel-nyukalo requested changes

2022-03-10 08:23 UTC, pavel-niukalo commented on styles/styles.css
> +}
Эти свойства невалидны для подключения шрифтов

2022-03-10 08:23 UTC, pavel-nyukalo commented on styles/styles.css
> +  font-family: "PT Sans", sans-serif;
Указав для `body` семейство шрифтов можно больше не прописывать его (для `input`, `button` и `select` надо будет указать `inherit`)

2022-03-10 08:23 UTC, pavel-nyukalo commented on styles/styles.css
> +  line-heiglay: swap;
Тут `line-height` хотел прописать?

2022-03-10 08:23 UTC, pavel-niukalo commented on styles/styles.css
> +  display: ;
Пустое свойство, тоже надо убрать, невалидно

2022-03-10 08:23 UTC, pavel-nyukalo commented on styles/styles.css
> +  width: 10ht: 26px;
Немного не понял вот эту запись, что тут подразумевалось?

2022-03-10 08:23 UTC, pavel-nyukalo commented on styles/styles.css
> +}
1. Предлагаю обернуть все в одну обертку общую (div), поскольку нам надо будет потом тень еще задавать, ей прописать ширину в 1200рх и тогда не надо будет везде прописывать 1200рх
2. Лучше не задавать жестко высоту, так верстка не пройдет тест на переполнение. Можешь пока убрать, а когда будешь строить сетки там уже за счет отступов и контента высота будет задаваться

2022-03-10 08:23 UTC, pavel-niukalo commented on styles/styles.css
> +  font-family: "PT Sans", sans-serif;
То же самое про семейство шрифтов

2022-03-10 08:23 UTC, pavel-nyukalo commented on styles/styles.css
> +  ont-weight: bold;
`font`*

2022-03-10 08:23 UTC, pavel-nyukalo commented on catalog.html
> +        <li class="photo-menu-button">
Про отступы я имел ввиду вот вложенность дочерних элементов
Тут элемент списка находится на том же уровне, что и сам список. А должен быть вложен в него (с отступом в 2 пробела), вот так:
```html
<ul>
  <li>
  </li>
</ul>
```
Сейчас вот так
```html
<ul>
<li>
</li>
</ul>
```

2022-03-11 16:52 UTC, pavel-nyukalo approved these changes

2022-03-11 16:52 UTC, merged